export const projects = [
  {
    title: 'Tennis Partner Landing + System',
    description: 'Custom build landing page, together with inside system for registered users with tournaments, marketplaces, tennis courts availability etc.',
    image: '/images/tpartneris.png',
    tags: ['React JS', 'Node JS', 'MySQL', 'Material UI', 'Figma'],
    website: 'https://tenisopartneris.lt/',
    visit: '',
    id: 1,
  },
  {
    title: 'Hand4Hand Poker Platform',
    description: 'Custom build poker platform with social media, user profiles, tournaments, events, venues, poker hands history etc.',
    image: '/images/h4h.png',
    tags: ['React JS', 'Tailwind-CSS', 'Figma'],
    website: 'https://hand4hand.com/',
    visit: '',
    id: 2,
  },
  {
    title: 'PanTenisas Teniso Aikštynas',
    description: 'Custom build landing page and tennis courts reservation system. Reservation system is connected with Stripe payments platform.',
    image: '/images/pantenisas.png',
    tags: ['React JS', 'Material UI', 'Node JS', 'MySQL', 'Stripe'],
    website: 'https://pantenisas.lt/',
    visit: '',
    id: 3,
  },
  {
    title: 'GrowthCut',
    description:
      'Custom build platform to process youtube videos to AI generated highlights with subtitles for social media sharing, also providing SEO keywords, descriptions etc.',
    image: '/images/growthcut.png',
    tags: ['React JS', 'Material UI', 'Node JS', 'MySQL', 'OpenAI', 'Figma'],
    website: 'https://growthcut.co/',
    visit: '',
    id: 4,
  },
  {
    title: 'HTM - High Tech Metal Australia made by K-Design',
    description: 'Custom build website following Figma design provided by UI/UX designer.',
    image: '/images/htm.png',
    tags: ['Next JS', 'CSS Modules', 'Sanity CMS', 'Figma'],
    website: 'https://hightechmedical.com.au/',
    visit: {
      title: 'K-Design',
      link: 'https://k-design.io/',
    },
    id: 5,
  },
  {
    title: 'Svarius - Cleaning Service',
    description: 'Custom build website with integrated Sanity CMS.',
    image: '/images/svarius.png',
    tags: ['Next JS', 'Material UI', 'Sanity CMS'],
    website: 'https://svarius.lt/',
    visit: '',
    id: 6,
  },
  {
    title: 'Aukstaitijos Padelio Klubas',
    description: 'Custom build padel courts reservation system with integrated Stripe payments platform.',
    image: '/images/padelis.png',
    tags: ['React JS', 'Material UI', 'Node JS', 'MySQL'],
    website: 'https://aukstaitijospadelioklubas.lt/',
    visit: '',
    id: 7,
  },
  {
    title: 'Marijampolės Teniso kortai',
    description: 'Custom build tennis courts reservation system.',
    image: '/images/mtenisas.png',
    tags: ['React JS', 'Material UI', 'Node JS', 'MySQL'],
    website: 'https://mtenisas.lt/',
    visit: '',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Shift Manager @ PMP in Amazon.co.uk' },
  { year: 2017, text: 'Shift Manager @ Adecco in Amazon.co.uk' },
  { year: 2018, text: 'Workforce Staffing Coordinator (HR) @ Amazon.co.uk' },
  {
    year: 2019,
    text: 'Process Expert in Compensation & Benefits (HR) @ SEB Global Services',
  },
  {
    year: 2021,
    text: '9 months junior full stack course @ CodeAcademy',
  },
  { year: 2022, text: 'Junior React developer @ 1T2B' },
  { year: 2022, text: 'Junior React developer @ TGLab/Kickertech' },
  { year: 2023, text: 'FreeLancer @ TKuprinskas' },
  { year: 2024, text: 'FreeLancer @ TKuprinskas' },
];
